apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cloudfloo.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "cloudfloo.name" . }}
    chart: {{ include "cloudfloo.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "cloudfloo.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ include "cloudfloo.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 3000
          name: http
        resources: {{- toYaml .Values.resources | nindent 10 }}
