replicaCount: 1

image:
  repository: ghcr.io/cloudfloo/cloudfloo.io
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

resources: {}

ingress:
  enabled: true
  className: nginx
  host: cloudfloo.io
  annotations: {}

